# Generated by Django 3.0.7 on 2020-06-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
