# Generated by Django 3.0.7 on 2020-06-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_auto_20200626_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='images',
        ),
    ]
