# Generated by Django 3.0.7 on 2020-06-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0005_remove_postimage_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='like',
        ),
        migrations.AddField(
            model_name='post',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
