# Generated by Django 3.0.7 on 2020-06-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0009_auto_20200626_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
