# Generated by Django 3.0.7 on 2020-06-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0010_auto_20200626_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
