# Generated by Django 3.0.7 on 2020-06-26 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0012_auto_20200626_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_identifier',
        ),
        migrations.CreateModel(
            name='UserPostAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disliked_posts', models.ManyToManyField(blank=True, related_name='disliked_posts', to='socialapp.Post')),
                ('liked_posts', models.ManyToManyField(blank=True, related_name='liked_posts', to='socialapp.Post')),
                ('user_identifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialapp.UserIdentifier')),
            ],
        ),
    ]
