# Generated by Django 3.0.7 on 2020-06-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0013_auto_20200626_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('l', 'Like'), ('d', 'Dislike'), ('n', 'No Action')], default='n', max_length=3),
        ),
    ]
