# Generated by Django 3.0.7 on 2020-06-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0014_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Liked', 'Like'), ('Disliked', 'Dislike'), ('No Action', 'No Action')], default='No Action', max_length=10),
        ),
    ]
