# Generated by Django 3.0.7 on 2020-06-26 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0015_auto_20200626_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialapp.UserIdentifier'),
        ),
    ]
